### ISSUE TITLE
Observations from using readme to build ripple on AWS workspace

### ISSUE THREAD

**Issue by BradfordBates-NOAA** [Dewberry/ripple1d#113]
- On the "Building from source" section, I couldn't figure out how to do the following steps, but I was still able to import ripple1d in Python. I don't have experience with .whl and it wasn't immediately clear to me how I should locate the file. But like I said, I was still able to import the package in Python, so I just skipped this.
```
pip install dist/*.whl

# Either have PowerShell get the file name or look in the dist/ directory for the latest .whl file
# Example filename: `ripple1d-0.3.0-py3-none-any.whl`
 $wheel = Get-ChildItem -Path dist -Filter *.whl | Select-Object -First 1
 pip install $wheel.FullName
```

- I had to install pytests on my Workspace using `pip install -U pytest`. 
- I ran the tests using the following, but it wasn't clear if this was the desired result. Consider adding documentation to verify the user's results are the expected results.
```D:\Users\bradford.bates\Documents\dev\ripple1d>pytest tests/
================================================= test session starts =================================================
platform win32 -- Python 3.12.4, pytest-8.3.2, pluggy-1.5.0
rootdir: D:\Users\bradford.bates\Documents\dev\ripple1d
configfile: pyproject.toml
collected 0 items

================================================ no tests ran in 0.03s ================================================
```

- The installation of Python in "Setting up a virtual environment" section seems misplaced given that Python was used earlier in the process. I already had Python installed so it was a non-issue for me, but could pose issues for others.

 ...more to follow as I keep going. I will directly edit this text block.

**Comment by ar-siddiqui** [comment]
From what I see the docs need to be separated for what purpose they are fulfilling, consumers such as ERT team should not need to be worried about tests and the instructions for them should not have tests, etc but setting up ripple and interacting with ripple and taking a sample model (Baxtar) from source model to FIM library stage.

So a Getting started for users/consumers of Ripple 
And a separate doc for devs that include testing and building from wheel etc.

**Comment by slawler** [comment]
We need to add schemas for data as well, adding this to the update list for docs.

**Comment by ar-siddiqui** [comment]
@slawler here is what I am envisioning

![image](https://github.com/user-attachments/assets/8482c147-bf71-46df-aaf5-5de997d0841c)
