### ISSUE TITLE
Conflation file structure

### ISSUE THREAD

**Issue by ar-siddiqui** [Dewberry/ripple1d#117]
The conflation JSON now have a new line at the end that is breaking production scripts.

![image](https://github.com/user-attachments/assets/ba614a85-4d93-450b-9f76-a6ca8af265e2)

I can update our scripts, but we must separate the reaches and other data in different containers. Currently, they are all at the same level. Something like
```JSON
"conflated_reaches": {...},
"otherdata": {...}

**Comment by mdeshotel** [comment]
| term | type | definition|
| :---: | :---: | :---:| 
| reaches | dict | Reaches associated with the ras model. Reach ids are the keys of the nested dicts which contain the conflation results/metrics.|
| us_xs | dict | Contains relevant HEC-RAS info for the most upstream cross section associated with the reach.| 
| ds_xs | dict | Contains relevant HEC-RAS info for the most downstream  cross section associated with the reach.| 
| river | str | The river name for the cross section as it was specified in the source HEC-RAS model.|
| reach | str | The reach name for the cross section as it was specified in the source HEC-RAS model.|
| xs_id | float | The river station for the cross section as it was specified in the source HEC-RAS model.|
| min_elevation | float | The minimum elevation in the cross section station-elevation data as it was specified in the source HEC-RAS model.|
| max_elevation | float | The maximum elevation in the cross section station-elevation data as it was specified in the source HEC-RAS model.|
| eclipsed | bool | Specifies if the reach has been eclipsed (covered) by an upstream or downstream reach. |
| low_flow_cfs | int | |
| high_flow_cfs | int | |
| network_to_id | str | The to_id as specified in the attributes of the input hydrofabric layer. |
| metrics | dict | Contains the conflation metrics for the reach. |
| xs | dict | Metrics describing the deviations between centerlines at cross section locationss for the source HEC-RAS model and the hydrofabric. |
| centerline_offset | dict | Metrics describing the distance between the point where the source HEC-RAS centerline intersects the cross sections and the point where the hydrofabric reach intersects the cross section. |
| thalweg_offset | dict | Metrics describing the distance between the source HEC-RAS's thalweg and the point where the hydrofabric reach intersects the cross section. |
| lengths | dict | Metrics comparing the lengths of source HEC-RAS model centerline and the hydrofabric reach. These are computed from the most upstream cross section to most down stream cross section associated with the hydrofabric network. |
| ras | int | Length of the source HEC-RAS centerline between the most upstream and most downstream cross sections associated with the hydrofabric network. |
| network | int | Length of hydrofabric network between the most upstream and most downstream cross sections associated with the hydrofabric reach. |
| coverage | dict | Metrics describing tha extent of the hydrofabric reach that is covered by the source HEC-RAS model. |
| start | float | The upstream limit where the source HEC-RAS model provides coverage. Provided as a ratio of the entire hydrofabric reach. |
| end | float | The downstream limit where the source HEC-RAS model provides coverage. Provided as a ratio of the entire hydrofabric reach. |
| overlapped_reaches | list | Reaches that intersect the cross sections of the current reach. |
| eclipsed_reaches | list | Reaches that are eclipsed (covered) by the cross sections of the current reach. |
| metadata | dict | Metadata for the conflation. |
| source_network | dict | Data summarizing the source network |
| file_name | str | Source network file name. |
| version | str | Source network version. |
| type | str | Source network type. |
| conflation_png | str | A png depicting the conflation results. |
| conflation_ripple1d_version | str | The version of ripple1d used to conflate the source HEC-RAS model with the source network. |
| metrics_ripple1d_version | str |  The version of ripple1d used to compute the conflation metric. |
| source_ras_model | dict | Metadata for the source HEC-RAS model. |
| stac_api | str | The stac api containing the source HEC-RAS model. |
| stac_collection_id | str | The stac collection containing the source HEC-RAS model. |
| stac_item_id | str | The stac item for the source HEC-RAS model. |
| source_ras_files | dict | files for the souce HEC-RAS model. |
| geometry | str | The geometry file used from the source HEC-RAS model. |
| forcing | str | The forcing file used from the source HEC-RAS model. |
| project-file | str | The project file used from the source HEC-RAS model. |
| plan | str | The plan file used from the source HEC-RAS model. |
| length_units | str | Units for the lengths specified in the conflation json. |
| flow_units | str | Units for the flows specified in the conflation json. |
```json
{
    "reaches": {
        "2826228": {
            "us_xs": {
                "river": "Baxter River",
                "reach": "Upper Reach",
                "min_elevation": 33.4,
                "max_elevation": 125.0,
                "xs_id": 84816.0
            },
            "ds_xs": {
                "river": "Baxter River",
                "reach": "Upper Reach",
                "min_elevation": 55.0,
                "max_elevation": 120.02,
                "xs_id": 84000.0
            },
            "eclipsed": false,
            "low_flow_cfs": 5668,
            "high_flow_cfs": 19588,
            "network_to_id": "2823932",
            "metrics": {
                "xs": {
                    "centerline_offset": {
                        "count": 2,
                        "mean": 14,
                        "std": 7,
                        "min": 9,
                        "10%": 10,
                        "20%": 11,
                        "30%": 12,
                        "40%": 13,
                        "50%": 14,
                        "60%": 15,
                        "70%": 16,
                        "80%": 17,
                        "90%": 18,
                        "100%": 19,
                        "max": 19
                    },
                    "thalweg_offset": {
                        "count": 2,
                        "mean": 383,
                        "std": 138,
                        "min": 286,
                        "10%": 305,
                        "20%": 325,
                        "30%": 344,
                        "40%": 364,
                        "50%": 383,
                        "60%": 403,
                        "70%": 422,
                        "80%": 442,
                        "90%": 461,
                        "100%": 481,
                        "max": 481
                    }
                },
                "lengths": {
                    "ras": 821,
                    "network": 838,
                    "network_to_ras_ratio": 1.02
                },
                "coverage": {
                    "start": 0.74,
                    "end": 1
                }
            },
            "overlapped_reaches": [],
            "eclipsed_reaches": []
        },
    },
    "metadata": {
        "source_network": {
            "file_name": "flows.parquet",
            "version": "2.1",
            "type": "nwm_hydrofabric"
        },
        "conflation_png": "Baxter.conflation.png",
        "conflation_ripple1d_version": "0.4.2",
        "metrics_ripple1d_version": "0.4.2",
        "source_ras_model": {
            "stac_api": "https://stac2.dewberryanalytics.com",
            "stac_collection_id": "ebfe-12090301_LowerColoradoCummins",
            "stac_item_id": "137a9667-e5cf-4cea-b6ec-2e882a42fdc8",
            "source_ras_files": {
                "geometry": "Baxter.g02",
                "forcing": "Baxter.f01",
                "project-file": "Baxter.prj",
                "plan": "Baxter.p01"
            }
        },
        "length_units": "feet",
        "flow_units": "cfs"
    }
}

```

*NOTE*: this example does not include an ecplipsd read...


```json
 "eclipsed_reaches": ["1293098","1293099"]
```

**Comment by ar-siddiqui** [comment]
@mdeshotel Overall looks great. Please see the attached markups in red for the terms description and here are some comments on JSON.

```JSON
{
    "reaches": {
        "2826228": {
            "us_xs": {
                "river": "Baxter River",
                "reach": "Upper Reach",
                "min_elevation": 33.4,
                "max_elevation": 125.0,
                "xs_id": 84816.0
            },
            "ds_xs": {
                "river": "Baxter River",
                "reach": "Upper Reach",
                "min_elevation": 55.0,
                "max_elevation": 120.02,
                "xs_id": 84000.0
            },
            "eclipsed": false,
            "low_flow_cfs": 5668, // cfs should be removed
            "high_flow_cfs": 19588, // cfs should be removed
            "network_to_id": "2823932",
            "metrics": {
                "xs": {
                    "centerline_offset": {
                        "count": 2,
                        "mean": 14,
                        "std": 7,
                        "min": 9, 
                        "10%": 10, // I think this is a lot of information, we should just have simple quartiles [11, 14, 17], but this is not a requirement
                        "20%": 11,
                        "30%": 12,
                        "40%": 13,
                        "50%": 14,
                        "60%": 15,
                        "70%": 16,
                        "80%": 17,
                        "90%": 18,
                        "100%": 19,
                        "max": 19
                    },
                    "thalweg_offset": {
                        "count": 2,
                        "mean": 383, // how come there is, this great of a difference when the centerline offset is only 14 feet
                        "std": 138,
                        "min": 286,
                        "10%": 305, // I think this is a lot of information, we should just have simple quartiles [11, 14, 17], but this is not a requirement
                        "20%": 325,
                        "30%": 344,
                        "40%": 364,
                        "50%": 383,
                        "60%": 403,
                        "70%": 422,
                        "80%": 442,
                        "90%": 461,
                        "100%": 481,
                        "max": 481
                    }
                },
                "lengths": {
                    "ras": 821,
                    "network": 838,
                    "network_to_ras_ratio": 1.02
                },
                "coverage": {
                    "start": 0.74,
                    "end": 1
                }
            },
            "overlapped_reaches": [],
            "eclipsed_reaches": []
        },
    },
    "metadata": {
        "source_network": {
            "file_name": "flows.parquet",
            "version": "2.1",
            "type": "nwm_hydrofabric"
        },
        "conflation_png": "Baxter.conflation.png",
        "conflation_ripple1d_version": "0.4.2",
        "metrics_ripple1d_version": "0.4.2",
        "source_ras_model": {
            "stac_api": "https://stac2.dewberryanalytics.com",
            "stac_collection_id": "ebfe-12090301_LowerColoradoCummins",
            "stac_item_id": "137a9667-e5cf-4cea-b6ec-2e882a42fdc8",
            "source_ras_files": {
                "geometry": "Baxter.g02",
                "forcing": "Baxter.f01",
                "project-file": "Baxter.prj",
                "plan": "Baxter.p01"
            }
        },
        "length_units": "feet",
        "flow_units": "cfs"
    }
}

```

[terms.docx](https://github.com/user-attachments/files/16914004/terms.docx)
