### ISSUE TITLE
`create_model_and_run_normal_depth` stuck in running state for two Baxter Reaches 

### ISSUE THREAD

**Issue by ar-siddiqui** [Dewberry/ripple1d#130]
The payload for the requests stuck in the running state

```JSON
{"submodel_directory": "D:\\\\Users\\\\bradford.bates\\\\workbench\\\\production\\\\submodels\\2820002", "plan_suffix": "ind", "num_of_discharges_for_initial_normal_depth_runs": 10, "ras_version": "631"}

{"submodel_directory": "D:\\\\Users\\\\bradford.bates\\\\workbench\\\\production\\\\submodels\\2823920", "plan_suffix": "ind", "num_of_discharges_for_initial_normal_depth_runs": 10, "ras_version": "631"}
```

![image](https://github.com/user-attachments/assets/a9c77267-2b1b-45cc-a84e-4338b6029add)

The subsequent steps such as `run_incrementa_depth` also fail, so it is not like the status is not being updated only. 

We should run automated tests for all Baxter reaches not just one reach.

**Comment by ar-siddiqui** [comment]
@BradfordBates-NOAA can you zip these two submodel folders and attach them here for debugging?

**Comment by BradfordBates-NOAA** [comment]
Here they are

[stuck_models.zip](https://github.com/user-attachments/files/16681907/stuck_models.zip)

**Comment by ar-siddiqui** [comment]
> We should run automated tests for all Baxter reaches not just one reach.

@slawler @mdeshotel If this causes problems with test runtimes, we can increase depth increments both in the flow range identification step and in the KWSE step.
