### ISSUE TITLE
ripple_version logic

### ISSUE THREAD

**Issue by ar-siddiqui** [Dewberry/ripple1d#131]
In v0.4.0, ripple_version is no longer required in POST payloads, but when provided what does it do? 
The ripple_version should never be an input in the request payload, it doesn't make sense to take the version from the input request.

Also IMO it is better not to write ripple1d_version in rating curve DB and should be recorded in reach STAC Item.

_Originally posted by @ar-siddiqui in https://github.com/Dewberry/ripple1d/issues/93#issuecomment-2299637471_

**Comment by mdeshotel** [comment]
I'll remove ripple_version as an optional arg for all processes. I can remove ripple1d_version from the rating curve  DB as well. The ripple1d_version should already be in the STAC items. Let me know if you are not seeing it.
