### ISSUE TITLE
bugs reported from extract_submodel step

### ISSUE THREAD

**Issue by slawler** [Dewberry/ripple1d#147]

**Comment by efdubya4** [comment]
- [ ] error 1: buffer too large (>10000ft) for clipping river to concave hull of cross sections. Check data for NWM Reach: 1465546.
Affected reach id's: 1465986, 1465546
Example Traceback: 
```Traceback (most recent call last):\n File "C:\venvs\ripple1d_0_4_2\Lib\site-packages\ripple1d\api\utils.py", line 31, in wrapper\n return_value = func(*args, **kwargs)\n ^^^^^^^^^^^^^^^^^^^^^\n File "C:\venvs\ripple1d_0_4_2\Lib\site-packages\ripple1d\api\tasks.py", line 208, in _process\n return func(**kwargs)\n ^^^^^^^^^^^^^^\n File "C:\venvs\ripple1d_0_4_2\Lib\site-packages\ripple1d\ops\subset_gpkg.py", line 471, in extract_submodel\n rgs.write_ripple_gpkg()\n File "C:\venvs\ripple1d_0_4_2\Lib\site-packages\ripple1d\ops\subset_gpkg.py", line 150, in write_ripple_gpkg\n for layer, gdf in self.subset_gdfs.items():\n ^^^^^^^^^^^^^^^^\n File "C:\venvs\ripple1d_0_4_2\Lib\site-packages\ripple1d\ops\subset_gpkg.py", line 127, in subset_gdfs\n ripple_river = self.clip_river(ripple_xs, ripple_river)\n ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n File "C:\venvs\ripple1d_0_4_2\Lib\site-packages\ripple1d\ops\subset_gpkg.py", line 428, in clip_river\n raise ValueError(\nValueError: buffer too large (>10000ft) for clipping river to concave hull of cross sections. Check data for NWM Reach: 1465546.\n ```

- [ ] error 2: 'NoneType' object has no attribute 'items'
Affected reach id's: 1465716, 1465774, 1466116, 1466196,1466364,1467758,1467774, 1467802, 1467872, 1467982,1468024, 1468026, 1468054, 1468314, 1468444.
Example Traceback:
```Traceback (most recent call last):\n File "C:\venvs\ripple1d_0_4_2\Lib\site-packages\ripple1d\api\utils.py", line 31, in wrapper\n return_value = func(*args, **kwargs)\n ^^^^^^^^^^^^^^^^^^^^^\n File "C:\venvs\ripple1d_0_4_2\Lib\site-packages\ripple1d\api\tasks.py", line 208, in _process\n return func(**kwargs)\n ^^^^^^^^^^^^^^\n File "C:\venvs\ripple1d_0_4_2\Lib\site-packages\ripple1d\ops\subset_gpkg.py", line 471, in extract_submodel\n rgs.write_ripple_gpkg()\n File "C:\venvs\ripple1d_0_4_2\Lib\site-packages\ripple1d\ops\subset_gpkg.py", line 150, in write_ripple_gpkg\n for layer, gdf in self.subset_gdfs.items():\n ^^^^^^^^^^^^^^^^^^^^^^\nAttributeError: 'NoneType' object has no attribute 'items'\n ```

**Comment by mdeshotel** [comment]
What data is this being ran on?

**Comment by ar-siddiqui** [comment]
Source models and a sample reach are:

For the first error:

https://radiantearth.github.io/stac-browser/#/external/stac2.dewberryanalytics.com/collections/ebfe-12040101_WestForkSanJacinto/items/b71cfa42-d1f0-4088-b817-2fa9275d7d40

1465546

For second error:

https://radiantearth.github.io/stac-browser/#/external/stac2.dewberryanalytics.com/collections/ebfe-12040101_WestForkSanJacinto/items/a035d9cb-6baa-40db-8b86-922d21f084f5

1465716

There is nothing in the submodels folders as this is the first step

**Comment by ar-siddiqui** [comment]
@slawler in which release we can target to have these bug fixes?

**Comment by slawler** [comment]
@mdeshotel can you take a look at these today?

**Comment by mdeshotel** [comment]
The first bug was being caused by bad geometry in the source model: 
![image](https://github.com/user-attachments/assets/918bf946-d128-40ac-a7ee-31eddb424316).
An intersection is now performed to determine if a cross section should be used. 
The second bug was being caused by having an upstream and downstream cross section that are the same. This is now checked during conflation and considered an eclipsed reach (we don't need to model it because it will be covered by the upstream/downstream reach).
