### ISSUE TITLE
Delete RAS grids when creating FIM library

### ISSUE THREAD

**Issue by ar-siddiqui** [Dewberry/ripple1d#151]
Have an argument for cleanup and if that is set to true, delete RAS grids.

Deleting them takes a long time, so better to delete them on the spot.

**Comment by mdeshotel** [comment]
By RAS grids, do you mean the raw RAS grids that have this naming: "Depth (5669).2823932.USGS_Seamless_DEM_13.tif" or the post-processed grids that have this naming "f_5669.tif"? Or possibly both?

**Comment by ar-siddiqui** [comment]
I mean raw RAS grids. What do you mean by `f_5669.tif`, that is the output of this process, so that should not be deleted but outputted in the user provided folder in #152

**Comment by mdeshotel** [comment]
Okay, that is what I thought. I just wanted to be sure.
