### ISSUE TITLE
Require a `library_directory` argument in `create_fim_lib` payload and write FIM Library directory there

### ISSUE THREAD

**Issue by ar-siddiqui** [Dewberry/ripple1d#152]
This should be a required argument and FIMs should always be written here.

If the `library_directory` is "C://FIM_library" then for a reach 2344565 the final result should look like this 

C://FIM_library
....... 2344565
............... z_nd
............... z_39_5
............... 2344565.db

**Comment by mdeshotel** [comment]
What will be in the "2344565" directory? is the model in there?

**Comment by ar-siddiqui** [comment]
No, that directory should be created.

**Comment by mdeshotel** [comment]
I see. It is more clear now that you updated the original comment. Thanks.
