### ISSUE TITLE
Parallel Processing Slows Down 'create_ras_terrain'

### ISSUE THREAD

**Issue by ar-siddiqui** [Dewberry/ripple1d#178]
If I use an S3 VRT as a source terrain, the performance worsens with increasing thread count in ripple API even though CPU/RAM utilization is below 5%. My first thought is this is because of RasterIO/GDAL competing for resources (such as file handlers for 100s of individual tiles in the VRT). I tried a Local Tiff as a source raster and it worked fine.

Here's a summary of my tests (avg times in minutes):

| **Test**             | **Z Drive** | **C Drive** | **USGS (10m)** | **Local TIFF** |
|----------------------|-------------|-------------|----------------|----------------|
| **1 Model (Serial)**  | 0.24        | 0.11        | 0.013          | 0.05           |
| **10 in Serial**      | 0.11        | 0.09        | 0.013          | N/A            |
| **10 in Parallel**    | 0.75        | 0.53        | Killed after 1 minute        | 0.04           |
| **18 in Parallel**    | 6.38        | 5.36        | Killed after 7 minute     | 0.05           |

I've tried tweaking `GDAL_NUM_THREADS`, `GDAL_CACHEMAX`, and `GDAL_MAX_DATASET_POOL_SIZE`, but parallel performance is still worse than serial.

This issue could be temporarily resolved in production by first creating a local TIFF for the working area, but the fundamental issue of resource competition between different processes is a bigger concern.

**Comment by ar-siddiqui** [comment]
Can we investigate this by printing logs and finding what function is taking a long time? I tried to reproduce this outside ripple and I couldn't. I also think this is not S3API rate limiting since 10 models are not large enough to cause rate limitation.

**Comment by ar-siddiqui** [comment]
I wrote this isolated script taking code from Ripple1D to benchmark parallel vs serial time and it did provide expected results. The parallel operations took on average half the time. So now I wonder why Ripple1D server with 96 cores is taking so long with parallel option.

```python
import time
from multiprocessing import Pool
import rasterio
from rasterio import mask
import os
from shapely.geometry import Polygon
from shapely import wkt


RASTER_FILE = '/vsicurl/https://rockyweb.usgs.gov/vdelivery/Datasets/Staged/Elevation/13/TIFF/USGS_Seamless_DEM_13.vrt'
OUTPUT_DIR = '/data'
NUM_PROCESSES =  4
PARALLEL = True 

# AOIs to extract data for
MASK_POLYGONS = [
    'Polygon ((-101.27354019513222738 35.52739919084066145, -101.27354019513222738 35.69615739573222868, -100.94487241384048559 35.69615739573222868, -100.94487241384048559 35.52739919084066145, -101.27354019513222738 35.52739919084066145))',
    'Polygon ((-102.00068677141113938 35.25089536155817882, -102.00068677141113938 35.3099018628973127, -101.84809101581141988 35.3099018628973127, -101.84809101581141988 35.25089536155817882, -102.00068677141113938 35.25089536155817882))',
    'Polygon ((-101.47061730459100204 35.31897596943801432, -101.47061730459100204 35.43785336400031838, -101.21361392673884438 35.43785336400031838, -101.21361392673884438 35.31897596943801432, -101.47061730459100204 35.31897596943801432))',
    'Polygon ((-101.59973679009847558 35.17417315916953413, -101.59973679009847558 35.24887728528475606, -101.26180206008611151 35.24887728528475606, -101.26180206008611151 35.17417315916953413, -101.59973679009847558 35.17417315916953413))',
]

def clip_raster(args):
    mask_polygon_wkt, idx = args
    output_path = os.path.join(OUTPUT_DIR, f'clip_{idx}.tif')
    if os.path.exists(output_path):
        os.remove(output_path)
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    print(f'Processing polygon {idx}')

    mask_polygon = wkt.loads(mask_polygon_wkt)


    with rasterio.open(RASTER_FILE) as src:
        out_meta = src.meta.copy()
        try:
            out_image, out_transform = mask.mask(src, [mask_polygon], all_touched=True, crop=True)
        except Exception as e:
            logging.error(f"Error clipping raster: {e}")
            return None
        out_meta.update({
            'height': out_image.shape[1],
            'width': out_image.shape[2],
            'transform': out_transform,
            'driver': 'GTiff',
        })
        with rasterio.open(output_path, 'w', **out_meta) as dest:
            dest.write(out_image)
    return output_path

def process_clips(mask_polygons_wkt, parallel=True, num_processes=4):
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    start_time = time.time()
    args_list = [(polygon_wkt, idx) for idx, polygon_wkt in enumerate(mask_polygons_wkt)]
    if parallel:
        with Pool(processes=num_processes) as pool:
            results = pool.map(clip_raster, args_list)
    else:
        results = []
        for args in args_list:
            result = clip_raster(args)
            results.append(result)
    end_time = time.time()
    print(f"Processing time ({'parallel' if parallel else 'serial'}): {end_time - start_time} seconds")
    return results

if __name__ == '__main__':

    process_clips(MASK_POLYGONS, parallel=PARALLEL, num_processes=NUM_PROCESSES)
```

**Comment by mxkpp** [comment]
@ar-siddiqui I am wondering if the USGS server (https://rockyweb.usgs.gov) could be rate-limiting. Could you please try using this direct S3 bucket path for the input VRT?

`/vsis3/prd-tnm/StagedProducts/Elevation/13/TIFF/USGS_Seamless_DEM_13.vrt`

You can browse files in that `prd-tnm` bucket through this interface:
https://prd-tnm.s3.amazonaws.com/index.html

---

If the direct S3 access does not solve the bottleneck, then I would wonder if rasterio and/or GDAL are not honoring the GDAL behavior variables that you have set (GDAL_NUM_THREADS, GDAL_MAX_DATASET_POOL_SIZE), depending on how/where those are being set. For example in a `.env` file versus in a `with rasterio.Env():` context manager.

**Comment by mxkpp** [comment]
The VRT in the `prd-tnm` bucket points to its own bucket for its tif paths, it does not point to `rockyweb.usgs.gov`.  Here's the first entry:

```xml
<SourceFilename relativeToVRT="0">/vsicurl/https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/13/TIFF/current/n06e162/USGS_13_n06e162.tif</SourceFilename>
```

**Comment by ar-siddiqui** [comment]
I see. I confused pointing to the rocky server with using `vsicurl` vs `vsis3`. I still don't think that is the issue. One can download the USGS file and test that way.

**Comment by mxkpp** [comment]
Sorry I should have mentioned earlier, we are looking into profiling as you suggested / testing under various conditions. I wanted to mention the alternate VRT source as it came to mind when we were looking this morning, before we'd had a chance to set up more cloud resources for further testing.

**Comment by slawler** [comment]
This issue results for internal 2 rasterio calls in the main function. The calls result in a competing of resources (threads) when executed by huey. The resolution is to ship the internal function calls to a dedicated core where

```python
 mask = get_geometry_mask(gdf_xs, terrain_source_url)
```

is replaced with 

```python
  with ProcessPoolExecutor() as executor:
      future = executor.submit(get_geometry_mask, gdf_xs=gdf_xs, MAP_DEM_UNCLIPPED_SRC_URL=terrain_source_url)
      mask = future.result()
```
