### ISSUE TITLE
Jobs should not remain indefinitely in the 'running' state

### ISSUE THREAD

**Issue by ar-siddiqui** [Dewberry/ripple1d#188]
Why do certain jobs remain indefinitely in the 'running' state? This has been a recurring issue. We've previously identified and resolved the underlying errors, but we should address at a high level why a process would remain stuck in the 'running' state. Unless there's an infinite loop or some blocking operation within the code, this behavior shouldn't occur.

Example #187 #130 #90

**Comment by slawler** [comment]
Dissmiss endpoint added to hanlde this in production, more information is needed to handle specfic use-cases.
