### ISSUE TITLE
NWM reaches spanning two RAS reaches without a junction may fail if d/s reach lengths are zero

### ISSUE THREAD

**Issue by sclaw** [Dewberry/ripple1d#217]
Sometimes the most d/s XS of a RAS model will have a d/s reach length of zero (depends on what the original modeler entered).  When the source model runs, that XS will have some d/s boundary condition and won't throw an error.  

If a NWM reach spans that XS and sections from the RAS reach downstream, it will include all of them in the same RAS reach in the sub model.  When the sub model goes to run, the most d/s XS from the u/s RAS reach will still have 0 d/s reach length and an error will be thrown.

Example:

Collection: mip_17090003
Model: uw_group04
Sub model: 23765337

![image](https://github.com/user-attachments/assets/3399128a-db85-4780-bb76-70b399aac901)
most d/s section of SquawCrk has 0 d/s reach length, so sub model will not run

**Comment by sclaw** [comment]
Another example:

Collection: mip_17090003
Model: uw_group23
Sub model: 23764961

**Comment by ar-siddiqui** [comment]
Related to #216

**Comment by sclaw** [comment]
Closing in favor of https://github.com/Dewberry/ripple1d/issues/222
