### ISSUE TITLE
In `create_rating_curves_db`, plans that are not available should not raise Exception

### ISSUE THREAD

**Issue by ar-siddiqui** [Dewberry/ripple1d#254]
They should be skipped with log message similar to behavior in 0.6.3 `create_fim_lib`.

**Comment by mdeshotel** [comment]
Please confirm requested intended behavior. From the API Interface, Schema, and Data Models document: 

"Notes:
What would happen if crete_fim_lib or create_rating_curves_db gets wrong plan suffix
i. Doesn’t exist > we should return some error
II user error > process normally"


My apologies if I misunderstand this but please confirm what is expected before we revert changes.

**Comment by ar-siddiqui** [comment]
The behavior should be same as for `create_fim_lib` please see my comment there.
