### ISSUE TITLE
ID column in GPKG tables

### ISSUE THREAD

**Issue by ar-siddiqui** [Dewberry/ripple1d#59]
1. All other columns are lowercase, ID column should be lowercase as well as DB columns are supposed to be lowercase.
2. Can we have a more descriptive name, since we already have fid column, is this the order of the source model?

**Comment by mdeshotel** [comment]
Adding the "ID" column is default pandas behavior. We can prevent the "ID" column from being written by providing the "ignore_index=True" arg since we aren't using the "ID" columns for anything.
