### ISSUE TITLE
Confirm the conflation behavior at the terminal reaches that have only 1 XS

### ISSUE THREAD

**Issue by ar-siddiqui** [Dewberry/ripple1d#84]
As discussed in the dev call, we need to confirm that the Red XS in both cases is not being left unaccounted for and is included in the adjacent NWM reach.

Plan View:

Case 1 - Source Model 1 U/S most NWM reach has only 1 XS
![image](https://github.com/user-attachments/assets/0156c39b-052a-4777-8390-ef1b4117b046)

Case 2 - Source Model 2 D/S most NWM reach has only 1 XS
![image](https://github.com/user-attachments/assets/80f60bfc-d486-4973-91b0-c83ccb48a83e)

**Comment by mdeshotel** [comment]
Confirmed; the red cross section will be considered for both cases. Note, however, that the red cross section will only be in one of the submodels; it will not be in both. This will cause a gap in the inundation map. This gap will happen between reach 2 and 3 for the first case and between reach 1 and 2 for the second case. For the first case all three reaches will have a submodel. For the second case only reach 1 and 3 will have submodels; the red cross section on reach 2 will be part of the reach 1 submodel.
