### ISSUE TITLE
Need to handle very large river stations (over 8 digits)

### ISSUE THREAD

**Issue by mdeshotel** [Dewberry/ripple1d#92]
Need to handle very large river stations (over 8 digits). This could maybe be handled once we have inferred the model units (also an issue)? -to convert from feet to miles. Although the river stations are not used in calculations so we could simply divide by 1000 or something. This would mess up the count of river miles though. 

If we infer the units as "English units" how can we infer if river station is in feet vs miles? Maybe we simply compute the length of river line between cross sections in feet and if it is close to the river stationing then we can infer that the river stations are in feet. Convert to miles if over 8 digits?

**Comment by ar-siddiqui** [comment]
@mdeshotel can we close this and create new issues based on learning.
