### ISSUE TITLE
Conflation with parpendicular reaches

### ISSUE THREAD

**Issue by ar-siddiqui** [Dewberry/ripple1d#98]
![image](https://github.com/user-attachments/assets/1c460b28-182f-4c11-9777-02489d3308f1)

https://fim.s3.amazonaws.com/stac/dev2/Crystal%20Creek-West%20Fork%20San%20Jacinto%20River/WHITE%20OAK%20CREEK%20WEST%20TRIB%20NO%201/WHITE%20OAK%20CREEK%20WEST%20TRIB%20NO%201-nwm_conflation.png

**Comment by slawler** [comment]
@mdeshotel lets add tests and documenation as we fix conflation edge cases.

**Comment by slawler** [comment]
The behavior stems from a similar issue to this edge case: no conflation due to the starting point of the ras models river extending far downstream from the xs’s. (I think🤨)

**Comment by mdeshotel** [comment]
This should have been closed with [release 0.5.0 of ripple1d](https://github.com/Dewberry/ripple1d/releases.html). This will no longer conflate because the most upstream cross section and most downstream cross section are the same.
